### ISSUE TITLE
[Bug]: Dropdown doesn't keep order of data from query

### ISSUE THREAD

**Issue by martonmesz** [evidence-dev/evidence#2456]
### Describe the bug

According to the documentation, by default the dropdown values would appear in the same order as in the query producing them, but it appears to put them in ascending order instead.

### Steps to Reproduce

Create SQL query named 'bug':
```
  SELECT unnest([3,2,1]) AS value
```

Create component using the query results:
`<Dropdown data={bug} name=bug value=value/>`

### System Info

```Shell
System:
    OS: macOS 13.6.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 146.37 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - /usr/local/bin/node
    npm: 10.8.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.3
  npmPackages:
    @evidence-dev/bigquery: ^2.0.7 => 2.0.7 
    @evidence-dev/core-components: ^4.7.2 => 4.7.2 
    @evidence-dev/csv: ^1.0.12 => 1.0.12 
    @evidence-dev/databricks: ^1.0.7 => 1.0.7 
    @evidence-dev/duckdb: ^1.0.11 => 1.0.11 
    @evidence-dev/evidence: ^39.1.1 => 39.1.1 
    @evidence-dev/motherduck: ^1.0.2 => 1.0.2 
    @evidence-dev/mssql: ^1.0.9 => 1.0.9 
    @evidence-dev/mysql: ^1.1.3 => 1.1.3 
    @evidence-dev/postgres: ^1.0.6 => 1.0.6 
    @evidence-dev/snowflake: ^1.1.0 => 1.1.0 
    @evidence-dev/sqlite: ^2.0.6 => 2.0.6 
    @evidence-dev/trino: ^1.0.7 => 1.0.7
```

### Severity

annoyance

### Additional Information, or Workarounds

Workaround: create a new column that represents the required order then use that for the order parameter of the component.

**Comment by zachstence** [comment]
I had some suspicion that we broke something when we [rewrote the Dropdown component](https://github.com/evidence-dev/evidence/pull/2301), but I created a project with an older version and it still sorts in ascending order.

@mcrascal @hughess Thoughts on if/how we should be sorting dropdown options by label/value? Maybe the behavior could be hinged on a prop?

**Comment by archiewood** [comment]
I have fixed the docs to reflect the actual behaviour. Will go out with next release.

**Comment by pax** [comment]
This still doesn't seem to be working. I have tried ordering the query, using the order option as in the documentation, even with a `defaultValue`.
The _dev_ version shows the initially selected year as the latest (max value), the _compiled/build_ version default selects the min value.

![Image](https://github.com/user-attachments/assets/704cfd0f-d7e1-46ed-9386-389c3f4e7f29)

Neither versions (dev/build) follow the ordering, either in SQL or in the component. 
I've then noticed that the dev version follows the ordering, but then it _'blinks'_  and resets the order, in the undesirable way.

I have noticed a similar pattern 'sometimes' when displaying some more intricate (query-wise) dynamic lists – for a split second upon loading the page the component renders, then after a auto refresh the component disappears.

![Image](https://github.com/user-attachments/assets/c499accc-4248-4e5c-8758-a2b26f4c36b2)

see also: https://github.com/evidence-dev/evidence/issues/3137
